#!/bin/bash

opt_dry_run=false
opt_verbose=false

function usage() {
    cat <<EOF
$(basename ${0}) is a tool for execute **fmt depending on file extension.

Usage:
    $(basename ${0}) [<options>] file1(, file2, ...)

Options:
    --dry-run, -n    print message but don't execute
    --help, -h       print this message
    --verbose, -v    print verbose message

EOF
}

function select_fmt_command() {
    if [[ $1 =~ \.go$ ]] ; then
        echo "gofmt"
    elif [[ $1 =~ \.rs$ ]] ; then
        echo "rustfmt"
    else
        echo ""
    fi
}

function do_fmt_command() {
    fmt_command=$(select_fmt_command $1)

    if [[ $fmt_command == "" ]] ; then
        echo $1 ": Suitable fmt command is not found."
        return
    fi

    if $opt_dry_run ; then
        echo $fmt_command $1 "(dry-run)"
    else
        if $opt_verbose ; then
           echo $fmt_command $1
        fi

        $($fmt_command $1)
    fi
}

if [[ $# -eq 0 ]] ; then
    usage
    exit
fi

while [[ $# -gt 0 ]]
do
    case ${1} in
        --debug|-d)
            set -x
            ;;
        --dry-run|-n)
            opt_dry_run=true
            ;;
        --help|-h)
            usage
            ;;
        --verbose|-v)
            opt_verbose=true
            ;;
        *)
            do_fmt_command $1
            ;;
    esac

    shift
done
